// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mj.proto

#ifndef PROTOBUF_mj_2eproto__INCLUDED
#define PROTOBUF_mj_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace qp_mj {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mj_2eproto();
void protobuf_AssignDesc_mj_2eproto();
void protobuf_ShutdownFile_mj_2eproto();

class qp_logic;
class qp_mj_game_start_notify;
class qp_mj_game_end_notify;
class qp_mj_oper_req;
class qp_mj_oper_notify;

enum ws_cmd {
  CMD_MJ_GAME_START_NOTIFY = 1001,
  CMD_MJ_GAME_END_NOTIFY = 1002,
  CMD_MJ_OPER_REQ = 1003,
  CMD_MJ_OPER_NOTIFY = 1004
};
bool ws_cmd_IsValid(int value);
const ws_cmd ws_cmd_MIN = CMD_MJ_GAME_START_NOTIFY;
const ws_cmd ws_cmd_MAX = CMD_MJ_OPER_NOTIFY;
const int ws_cmd_ARRAYSIZE = ws_cmd_MAX + 1;

const ::google::protobuf::EnumDescriptor* ws_cmd_descriptor();
inline const ::std::string& ws_cmd_Name(ws_cmd value) {
  return ::google::protobuf::internal::NameOfEnum(
    ws_cmd_descriptor(), value);
}
inline bool ws_cmd_Parse(
    const ::std::string& name, ws_cmd* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ws_cmd>(
    ws_cmd_descriptor(), name, value);
}
// ===================================================================

class qp_logic : public ::google::protobuf::Message {
 public:
  qp_logic();
  virtual ~qp_logic();

  qp_logic(const qp_logic& from);

  inline qp_logic& operator=(const qp_logic& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const qp_logic& default_instance();

  void Swap(qp_logic* other);

  // implements Message ----------------------------------------------

  qp_logic* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const qp_logic& from);
  void MergeFrom(const qp_logic& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // optional bytes serialized = 3;
  inline bool has_serialized() const;
  inline void clear_serialized();
  static const int kSerializedFieldNumber = 3;
  inline const ::std::string& serialized() const;
  inline void set_serialized(const ::std::string& value);
  inline void set_serialized(const char* value);
  inline void set_serialized(const void* value, size_t size);
  inline ::std::string* mutable_serialized();
  inline ::std::string* release_serialized();
  inline void set_allocated_serialized(::std::string* serialized);

  // @@protoc_insertion_point(class_scope:qp_mj.qp_logic)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_serialized();
  inline void clear_has_serialized();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* serialized_;
  ::google::protobuf::int32 cmd_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_mj_2eproto();
  friend void protobuf_AssignDesc_mj_2eproto();
  friend void protobuf_ShutdownFile_mj_2eproto();

  void InitAsDefaultInstance();
  static qp_logic* default_instance_;
};
// -------------------------------------------------------------------

class qp_mj_game_start_notify : public ::google::protobuf::Message {
 public:
  qp_mj_game_start_notify();
  virtual ~qp_mj_game_start_notify();

  qp_mj_game_start_notify(const qp_mj_game_start_notify& from);

  inline qp_mj_game_start_notify& operator=(const qp_mj_game_start_notify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const qp_mj_game_start_notify& default_instance();

  void Swap(qp_mj_game_start_notify* other);

  // implements Message ----------------------------------------------

  qp_mj_game_start_notify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const qp_mj_game_start_notify& from);
  void MergeFrom(const qp_mj_game_start_notify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 pai = 1;
  inline int pai_size() const;
  inline void clear_pai();
  static const int kPaiFieldNumber = 1;
  inline ::google::protobuf::uint32 pai(int index) const;
  inline void set_pai(int index, ::google::protobuf::uint32 value);
  inline void add_pai(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pai() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pai();

  // required int32 banker_seat_number = 2;
  inline bool has_banker_seat_number() const;
  inline void clear_banker_seat_number();
  static const int kBankerSeatNumberFieldNumber = 2;
  inline ::google::protobuf::int32 banker_seat_number() const;
  inline void set_banker_seat_number(::google::protobuf::int32 value);

  // optional uint32 oper_flag = 3;
  inline bool has_oper_flag() const;
  inline void clear_oper_flag();
  static const int kOperFlagFieldNumber = 3;
  inline ::google::protobuf::uint32 oper_flag() const;
  inline void set_oper_flag(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:qp_mj.qp_mj_game_start_notify)
 private:
  inline void set_has_banker_seat_number();
  inline void clear_has_banker_seat_number();
  inline void set_has_oper_flag();
  inline void clear_has_oper_flag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pai_;
  ::google::protobuf::int32 banker_seat_number_;
  ::google::protobuf::uint32 oper_flag_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_mj_2eproto();
  friend void protobuf_AssignDesc_mj_2eproto();
  friend void protobuf_ShutdownFile_mj_2eproto();

  void InitAsDefaultInstance();
  static qp_mj_game_start_notify* default_instance_;
};
// -------------------------------------------------------------------

class qp_mj_game_end_notify : public ::google::protobuf::Message {
 public:
  qp_mj_game_end_notify();
  virtual ~qp_mj_game_end_notify();

  qp_mj_game_end_notify(const qp_mj_game_end_notify& from);

  inline qp_mj_game_end_notify& operator=(const qp_mj_game_end_notify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const qp_mj_game_end_notify& default_instance();

  void Swap(qp_mj_game_end_notify* other);

  // implements Message ----------------------------------------------

  qp_mj_game_end_notify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const qp_mj_game_end_notify& from);
  void MergeFrom(const qp_mj_game_end_notify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline ::google::protobuf::uint32 a() const;
  inline void set_a(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:qp_mj.qp_mj_game_end_notify)
 private:
  inline void set_has_a();
  inline void clear_has_a();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 a_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_mj_2eproto();
  friend void protobuf_AssignDesc_mj_2eproto();
  friend void protobuf_ShutdownFile_mj_2eproto();

  void InitAsDefaultInstance();
  static qp_mj_game_end_notify* default_instance_;
};
// -------------------------------------------------------------------

class qp_mj_oper_req : public ::google::protobuf::Message {
 public:
  qp_mj_oper_req();
  virtual ~qp_mj_oper_req();

  qp_mj_oper_req(const qp_mj_oper_req& from);

  inline qp_mj_oper_req& operator=(const qp_mj_oper_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const qp_mj_oper_req& default_instance();

  void Swap(qp_mj_oper_req* other);

  // implements Message ----------------------------------------------

  qp_mj_oper_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const qp_mj_oper_req& from);
  void MergeFrom(const qp_mj_oper_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional uint32 v1 = 2;
  inline bool has_v1() const;
  inline void clear_v1();
  static const int kV1FieldNumber = 2;
  inline ::google::protobuf::uint32 v1() const;
  inline void set_v1(::google::protobuf::uint32 value);

  // optional uint32 v2 = 3;
  inline bool has_v2() const;
  inline void clear_v2();
  static const int kV2FieldNumber = 3;
  inline ::google::protobuf::uint32 v2() const;
  inline void set_v2(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:qp_mj.qp_mj_oper_req)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_v1();
  inline void clear_has_v1();
  inline void set_has_v2();
  inline void clear_has_v2();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 v1_;
  ::google::protobuf::uint32 v2_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_mj_2eproto();
  friend void protobuf_AssignDesc_mj_2eproto();
  friend void protobuf_ShutdownFile_mj_2eproto();

  void InitAsDefaultInstance();
  static qp_mj_oper_req* default_instance_;
};
// -------------------------------------------------------------------

class qp_mj_oper_notify : public ::google::protobuf::Message {
 public:
  qp_mj_oper_notify();
  virtual ~qp_mj_oper_notify();

  qp_mj_oper_notify(const qp_mj_oper_notify& from);

  inline qp_mj_oper_notify& operator=(const qp_mj_oper_notify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const qp_mj_oper_notify& default_instance();

  void Swap(qp_mj_oper_notify* other);

  // implements Message ----------------------------------------------

  qp_mj_oper_notify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const qp_mj_oper_notify& from);
  void MergeFrom(const qp_mj_oper_notify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 seat_numer = 1;
  inline bool has_seat_numer() const;
  inline void clear_seat_numer();
  static const int kSeatNumerFieldNumber = 1;
  inline ::google::protobuf::int32 seat_numer() const;
  inline void set_seat_numer(::google::protobuf::int32 value);

  // required uint32 type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional uint32 v1 = 3;
  inline bool has_v1() const;
  inline void clear_v1();
  static const int kV1FieldNumber = 3;
  inline ::google::protobuf::uint32 v1() const;
  inline void set_v1(::google::protobuf::uint32 value);

  // optional uint32 v2 = 4;
  inline bool has_v2() const;
  inline void clear_v2();
  static const int kV2FieldNumber = 4;
  inline ::google::protobuf::uint32 v2() const;
  inline void set_v2(::google::protobuf::uint32 value);

  // optional int32 next_oper_seat_num = 5;
  inline bool has_next_oper_seat_num() const;
  inline void clear_next_oper_seat_num();
  static const int kNextOperSeatNumFieldNumber = 5;
  inline ::google::protobuf::int32 next_oper_seat_num() const;
  inline void set_next_oper_seat_num(::google::protobuf::int32 value);

  // optional uint32 next_oper_flag = 6;
  inline bool has_next_oper_flag() const;
  inline void clear_next_oper_flag();
  static const int kNextOperFlagFieldNumber = 6;
  inline ::google::protobuf::uint32 next_oper_flag() const;
  inline void set_next_oper_flag(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:qp_mj.qp_mj_oper_notify)
 private:
  inline void set_has_seat_numer();
  inline void clear_has_seat_numer();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_v1();
  inline void clear_has_v1();
  inline void set_has_v2();
  inline void clear_has_v2();
  inline void set_has_next_oper_seat_num();
  inline void clear_has_next_oper_seat_num();
  inline void set_has_next_oper_flag();
  inline void clear_has_next_oper_flag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 seat_numer_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 v1_;
  ::google::protobuf::uint32 v2_;
  ::google::protobuf::int32 next_oper_seat_num_;
  ::google::protobuf::uint32 next_oper_flag_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_mj_2eproto();
  friend void protobuf_AssignDesc_mj_2eproto();
  friend void protobuf_ShutdownFile_mj_2eproto();

  void InitAsDefaultInstance();
  static qp_mj_oper_notify* default_instance_;
};
// ===================================================================


// ===================================================================

// qp_logic

// required int32 cmd = 1;
inline bool qp_logic::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void qp_logic::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void qp_logic::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void qp_logic::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 qp_logic::cmd() const {
  return cmd_;
}
inline void qp_logic::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
}

// optional bytes serialized = 3;
inline bool qp_logic::has_serialized() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void qp_logic::set_has_serialized() {
  _has_bits_[0] |= 0x00000002u;
}
inline void qp_logic::clear_has_serialized() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void qp_logic::clear_serialized() {
  if (serialized_ != &::google::protobuf::internal::kEmptyString) {
    serialized_->clear();
  }
  clear_has_serialized();
}
inline const ::std::string& qp_logic::serialized() const {
  return *serialized_;
}
inline void qp_logic::set_serialized(const ::std::string& value) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(value);
}
inline void qp_logic::set_serialized(const char* value) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(value);
}
inline void qp_logic::set_serialized(const void* value, size_t size) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* qp_logic::mutable_serialized() {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  return serialized_;
}
inline ::std::string* qp_logic::release_serialized() {
  clear_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = serialized_;
    serialized_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void qp_logic::set_allocated_serialized(::std::string* serialized) {
  if (serialized_ != &::google::protobuf::internal::kEmptyString) {
    delete serialized_;
  }
  if (serialized) {
    set_has_serialized();
    serialized_ = serialized;
  } else {
    clear_has_serialized();
    serialized_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// qp_mj_game_start_notify

// repeated uint32 pai = 1;
inline int qp_mj_game_start_notify::pai_size() const {
  return pai_.size();
}
inline void qp_mj_game_start_notify::clear_pai() {
  pai_.Clear();
}
inline ::google::protobuf::uint32 qp_mj_game_start_notify::pai(int index) const {
  return pai_.Get(index);
}
inline void qp_mj_game_start_notify::set_pai(int index, ::google::protobuf::uint32 value) {
  pai_.Set(index, value);
}
inline void qp_mj_game_start_notify::add_pai(::google::protobuf::uint32 value) {
  pai_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
qp_mj_game_start_notify::pai() const {
  return pai_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
qp_mj_game_start_notify::mutable_pai() {
  return &pai_;
}

// required int32 banker_seat_number = 2;
inline bool qp_mj_game_start_notify::has_banker_seat_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void qp_mj_game_start_notify::set_has_banker_seat_number() {
  _has_bits_[0] |= 0x00000002u;
}
inline void qp_mj_game_start_notify::clear_has_banker_seat_number() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void qp_mj_game_start_notify::clear_banker_seat_number() {
  banker_seat_number_ = 0;
  clear_has_banker_seat_number();
}
inline ::google::protobuf::int32 qp_mj_game_start_notify::banker_seat_number() const {
  return banker_seat_number_;
}
inline void qp_mj_game_start_notify::set_banker_seat_number(::google::protobuf::int32 value) {
  set_has_banker_seat_number();
  banker_seat_number_ = value;
}

// optional uint32 oper_flag = 3;
inline bool qp_mj_game_start_notify::has_oper_flag() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void qp_mj_game_start_notify::set_has_oper_flag() {
  _has_bits_[0] |= 0x00000004u;
}
inline void qp_mj_game_start_notify::clear_has_oper_flag() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void qp_mj_game_start_notify::clear_oper_flag() {
  oper_flag_ = 0u;
  clear_has_oper_flag();
}
inline ::google::protobuf::uint32 qp_mj_game_start_notify::oper_flag() const {
  return oper_flag_;
}
inline void qp_mj_game_start_notify::set_oper_flag(::google::protobuf::uint32 value) {
  set_has_oper_flag();
  oper_flag_ = value;
}

// -------------------------------------------------------------------

// qp_mj_game_end_notify

// required uint32 a = 1;
inline bool qp_mj_game_end_notify::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void qp_mj_game_end_notify::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void qp_mj_game_end_notify::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void qp_mj_game_end_notify::clear_a() {
  a_ = 0u;
  clear_has_a();
}
inline ::google::protobuf::uint32 qp_mj_game_end_notify::a() const {
  return a_;
}
inline void qp_mj_game_end_notify::set_a(::google::protobuf::uint32 value) {
  set_has_a();
  a_ = value;
}

// -------------------------------------------------------------------

// qp_mj_oper_req

// required uint32 type = 1;
inline bool qp_mj_oper_req::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void qp_mj_oper_req::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void qp_mj_oper_req::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void qp_mj_oper_req::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 qp_mj_oper_req::type() const {
  return type_;
}
inline void qp_mj_oper_req::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// optional uint32 v1 = 2;
inline bool qp_mj_oper_req::has_v1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void qp_mj_oper_req::set_has_v1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void qp_mj_oper_req::clear_has_v1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void qp_mj_oper_req::clear_v1() {
  v1_ = 0u;
  clear_has_v1();
}
inline ::google::protobuf::uint32 qp_mj_oper_req::v1() const {
  return v1_;
}
inline void qp_mj_oper_req::set_v1(::google::protobuf::uint32 value) {
  set_has_v1();
  v1_ = value;
}

// optional uint32 v2 = 3;
inline bool qp_mj_oper_req::has_v2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void qp_mj_oper_req::set_has_v2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void qp_mj_oper_req::clear_has_v2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void qp_mj_oper_req::clear_v2() {
  v2_ = 0u;
  clear_has_v2();
}
inline ::google::protobuf::uint32 qp_mj_oper_req::v2() const {
  return v2_;
}
inline void qp_mj_oper_req::set_v2(::google::protobuf::uint32 value) {
  set_has_v2();
  v2_ = value;
}

// -------------------------------------------------------------------

// qp_mj_oper_notify

// required int32 seat_numer = 1;
inline bool qp_mj_oper_notify::has_seat_numer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void qp_mj_oper_notify::set_has_seat_numer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void qp_mj_oper_notify::clear_has_seat_numer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void qp_mj_oper_notify::clear_seat_numer() {
  seat_numer_ = 0;
  clear_has_seat_numer();
}
inline ::google::protobuf::int32 qp_mj_oper_notify::seat_numer() const {
  return seat_numer_;
}
inline void qp_mj_oper_notify::set_seat_numer(::google::protobuf::int32 value) {
  set_has_seat_numer();
  seat_numer_ = value;
}

// required uint32 type = 2;
inline bool qp_mj_oper_notify::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void qp_mj_oper_notify::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void qp_mj_oper_notify::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void qp_mj_oper_notify::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 qp_mj_oper_notify::type() const {
  return type_;
}
inline void qp_mj_oper_notify::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// optional uint32 v1 = 3;
inline bool qp_mj_oper_notify::has_v1() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void qp_mj_oper_notify::set_has_v1() {
  _has_bits_[0] |= 0x00000004u;
}
inline void qp_mj_oper_notify::clear_has_v1() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void qp_mj_oper_notify::clear_v1() {
  v1_ = 0u;
  clear_has_v1();
}
inline ::google::protobuf::uint32 qp_mj_oper_notify::v1() const {
  return v1_;
}
inline void qp_mj_oper_notify::set_v1(::google::protobuf::uint32 value) {
  set_has_v1();
  v1_ = value;
}

// optional uint32 v2 = 4;
inline bool qp_mj_oper_notify::has_v2() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void qp_mj_oper_notify::set_has_v2() {
  _has_bits_[0] |= 0x00000008u;
}
inline void qp_mj_oper_notify::clear_has_v2() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void qp_mj_oper_notify::clear_v2() {
  v2_ = 0u;
  clear_has_v2();
}
inline ::google::protobuf::uint32 qp_mj_oper_notify::v2() const {
  return v2_;
}
inline void qp_mj_oper_notify::set_v2(::google::protobuf::uint32 value) {
  set_has_v2();
  v2_ = value;
}

// optional int32 next_oper_seat_num = 5;
inline bool qp_mj_oper_notify::has_next_oper_seat_num() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void qp_mj_oper_notify::set_has_next_oper_seat_num() {
  _has_bits_[0] |= 0x00000010u;
}
inline void qp_mj_oper_notify::clear_has_next_oper_seat_num() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void qp_mj_oper_notify::clear_next_oper_seat_num() {
  next_oper_seat_num_ = 0;
  clear_has_next_oper_seat_num();
}
inline ::google::protobuf::int32 qp_mj_oper_notify::next_oper_seat_num() const {
  return next_oper_seat_num_;
}
inline void qp_mj_oper_notify::set_next_oper_seat_num(::google::protobuf::int32 value) {
  set_has_next_oper_seat_num();
  next_oper_seat_num_ = value;
}

// optional uint32 next_oper_flag = 6;
inline bool qp_mj_oper_notify::has_next_oper_flag() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void qp_mj_oper_notify::set_has_next_oper_flag() {
  _has_bits_[0] |= 0x00000020u;
}
inline void qp_mj_oper_notify::clear_has_next_oper_flag() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void qp_mj_oper_notify::clear_next_oper_flag() {
  next_oper_flag_ = 0u;
  clear_has_next_oper_flag();
}
inline ::google::protobuf::uint32 qp_mj_oper_notify::next_oper_flag() const {
  return next_oper_flag_;
}
inline void qp_mj_oper_notify::set_next_oper_flag(::google::protobuf::uint32 value) {
  set_has_next_oper_flag();
  next_oper_flag_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace qp_mj

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::qp_mj::ws_cmd>() {
  return ::qp_mj::ws_cmd_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mj_2eproto__INCLUDED
