-record(qp_packet, {cmd, seq_id, body}).
-record(login_req, {acc}).
-record(login_rsp, {state}).
-record(create_room_req, {room_type, ready_state}).
-record(create_room_rsp, {state, room_id}).
-record(join_room_req, {room_id}).
-record(room_user, {seat_id}).
-record(join_room_rsp, {state, users}).
-record(ready_req, {id}).
-record(ready_rsp, {state}).
-record(game_data, {data}).
